CREATE TABLE emprestimos (
                            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                            dataEmprestimo DATE NOT NULL,
                            dataDevolucao DATE,
                            usuario_id BIGINT NOT NULL,
                            FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
                            CONSTRAINT emprestimos_pkey PRIMARY KEY (id)
);
CREATE TABLE emprestimoItem (
                                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                                livro_id BIGINT NOT NULL,
                                emprestimo_id BIGINT NOT NULL,
                                FOREIGN KEY (livro_id) REFERENCES livros(id),
                                FOREIGN KEY (emprestimo_id) REFERENCES emprestimos(id)
);
